FUNCTION "EnS_Archive_CycInt500msFC" : Void
TITLE = FC for archiving functionality in cyclic interrupt OB
{ S7_Optimized_Access := 'TRUE' }
AUTHOR : Siemens
FAMILY : EnS
VERSION : 1.0
//FC for archiving functionality in cyclic interrupt OB

BEGIN
	
	//Archiving of buffer to HMI
	"EnS_Archive32469"(sD := "EnS_Archive32469".status,
	                   orgData := "EnS_Org_CycInt500ms".orgData,
	                   bufferWork := "EnS_BufferWork32469");
	
END_FUNCTION

