ORGANIZATION_BLOCK "EnS_CycInt500msOB"
TITLE = Cyclic interrupt OB of 500ms
{ S7_Optimized_Access := 'TRUE' }
AUTHOR : Siemens
FAMILY : EnS
VERSION : 1.0
//Cyclic interrupt OB of 500ms

BEGIN
	//FC for organizational data in cyclic interrupt OB
	"EnS_Org_CycInt500msFC"();
	//FC for time synchronization in cyclic interrupt OB
	"EnS_Sync_CycInt500msFC"();
	//FC for archiving functionality in cyclic interrupt OB
	"EnS_Archive_CycInt500msFC"();
	
END_ORGANIZATION_BLOCK

